// Generated by Demiurge. Do not edit by hand.
import "demiurge";
import type { PathValue } from "demiurge";

declare module "demiurge" {
  interface RoutePathVars {
    "/": {};
    "/api/health": {};
    "/blog": {};
    "/blog/[slug]": { slug: PathValue };
    "/old-blog": {};
  }

  interface RouteConcretePaths {
    "/": "/";
    "/api/health": "/api/health";
    "/blog": "/blog";
    "/blog/[slug]": `/blog/${PathValue}`;
    "/old-blog": "/old-blog";
  }
}

export {};
