import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { PACKAGE_NAME } from "../package-name";

export type GenerateRoutesOptions = {
  locales?: readonly string[];
  localeNamespaces?: readonly string[];
  outputFile: string;
  routesDir: string;
};

type RouteInfo = {
  contextMiddleware: number[];
  fileSegments: string[];
  importPath: string;
  pathVars: string[];
  pattern: string;
};

type MiddlewareInfo = {
  file: string;
  fileSegments: string[];
  importPath: string;
};

export async function generateRoutes(options: GenerateRoutesOptions) {
  const routeFiles = await findRouteFiles(options.routesDir);
  const middleware = routeFiles
    .map((file) => toMiddlewareInfo(options, file))
    .filter((value): value is MiddlewareInfo => Boolean(value));
  const routes = routeFiles
    .map((file) => toRouteInfo(options, file, middleware))
    .filter((route): route is RouteInfo => Boolean(route))
    .sort((a, b) => a.pattern.localeCompare(b.pattern));
  assertLocaleNamespaceCollisions(routes, options.localeNamespaces ?? []);

  const source = renderRoutesModule(routes, middleware, options.locales);

  await mkdir(dirname(options.outputFile), { recursive: true });
  await writeFile(options.outputFile, source);

  return {
    routes,
    source,
  };
}

function assertLocaleNamespaceCollisions(routes: RouteInfo[], namespaces: readonly string[]) {
  const localeSegments = new Set(namespaces.map((value) => value.toLowerCase()));
  for (const route of routes) {
    const [segment] = route.pattern.slice(1).split("/");
    if (segment && !segment.startsWith("[") && localeSegments.has(segment.toLowerCase())) {
      throw new Error(
        `Route "${route.pattern}" conflicts with the locale URL namespace "${segment}". Move the route or change the locale label.`,
      );
    }
  }
}

async function findRouteFiles(directory: string) {
  const entries = await readdir(directory, {
    recursive: true,
    withFileTypes: true,
  });

  return entries
    .filter((entry) => entry.isFile() && /\.tsx?$/.test(entry.name))
    .map((entry) => resolve(entry.parentPath, entry.name));
}

function toRouteInfo(
  options: GenerateRoutesOptions,
  file: string,
  middleware: MiddlewareInfo[],
) {
  const relativePath = relative(options.routesDir, file).split(sep).join("/");
  const fileSegments = relativePath.replace(/\.tsx?$/, "").split("/");
  const basename = fileSegments.at(-1);

  if (basename?.startsWith("@")) {
    return null;
  }

  const urlSegments = fileSegments.flatMap((segment) => {
    if (isRouteGroupSegment(segment)) {
      return [];
    }

    if (segment === "index") {
      return [];
    }

    if (segment.startsWith("[...") && segment.endsWith("]")) {
      return [segment];
    }

    if (segment.startsWith("[") && segment.endsWith("]")) {
      return [segment];
    }

    return [segment];
  });

  const pathVars = fileSegments.flatMap((segment) => {
    if (isRouteGroupSegment(segment)) {
      return [];
    }

    if (segment.startsWith("[...") && segment.endsWith("]")) {
      return [segment.slice(4, -1)];
    }

    if (segment.startsWith("[") && segment.endsWith("]")) {
      return [segment.slice(1, -1)];
    }

    return [];
  });

  return {
    contextMiddleware: middleware
      .filter((entry) => isAttachedFileForRoute(entry.fileSegments, fileSegments))
      .map((entry) => middleware.indexOf(entry)),
    fileSegments,
    importPath: toImportPath(options.outputFile, file),
    pathVars,
    pattern: `/${urlSegments.join("/")}`.replace(/\/$/, "") || "/",
  };
}

function toMiddlewareInfo(
  options: GenerateRoutesOptions,
  file: string,
): MiddlewareInfo | null {
  const relativePath = relative(options.routesDir, file).split(sep).join("/");
  const fileSegments = relativePath.replace(/\.tsx?$/, "").split("/");

  if (fileSegments.at(-1) !== "@middleware") {
    return null;
  }

  return {
    file,
    fileSegments: fileSegments.slice(0, -1),
    importPath: toImportPath(options.outputFile, file),
  };
}

function toImportPath(outputFile: string, file: string) {
  let importPath = relative(dirname(outputFile), file)
    .split(sep)
    .join("/")
    .replace(/\.tsx?$/, "");

  if (!importPath.startsWith(".")) importPath = `./${importPath}`;
  return importPath;
}

function isAttachedFileForRoute(
  attachedFileSegments: string[],
  routeFileSegments: string[],
) {
  return attachedFileSegments.every(
    (segment, index) => routeFileSegments[index] === segment,
  );
}

function isRouteGroupSegment(segment: string) {
  return segment.startsWith("(") && segment.endsWith(")");
}

function renderRoutesModule(routes: RouteInfo[], middleware: MiddlewareInfo[], locales: readonly string[] = []) {
  return `// Generated by Demiurge. Do not edit by hand.
import "${PACKAGE_NAME}";
import type { MiddlewareContextOf, MutationMethodsOf, PathValue } from "${PACKAGE_NAME}";
${middleware.map(renderMiddlewareImport).join("\n")}

${middleware.map((_entry, index) => renderMiddlewareContextAlias(index)).join("\n")}

declare module "${PACKAGE_NAME}" {
  interface RouteLocales {
${locales.map((locale) => `    ${JSON.stringify(locale)}: true;`).join("\n")}
  }

  interface RoutePathVars {
${routes.map(renderPathVarsEntry).join("\n")}
  }

  interface RouteConcretePaths {
${routes.map(renderConcretePathEntry).join("\n")}
  }

  interface RouteRequestContexts {
${routes.map(renderRequestContextEntry).join("\n")}
  }

  interface RouteMutationMethods {
${routes.map(renderMutationMethodsEntry).join("\n")}
  }
}

export {};
`;
}

function renderMiddlewareImport(entry: MiddlewareInfo, index: number) {
  return `type __DemiurgeMiddleware${index} = typeof import(${JSON.stringify(entry.importPath)}) extends { middleware?: infer T } ? T : never;`;
}

function renderMiddlewareContextAlias(index: number) {
  return `type __DemiurgeMiddlewareContext${index} = MiddlewareContextOf<__DemiurgeMiddleware${index}>;`;
}

function renderPathVarsEntry(route: RouteInfo) {
  if (route.pathVars.length === 0) {
    return `    ${JSON.stringify(route.pattern)}: {};`;
  }

  const pathType = route.pathVars
    .map((name) => `${name}: PathValue`)
    .join("; ");

  return `    ${JSON.stringify(route.pattern)}: { ${pathType} };`;
}

function renderConcretePathEntry(route: RouteInfo) {
  return `    ${JSON.stringify(route.pattern)}: ${toConcretePathType(route.pattern)};`;
}

function renderRequestContextEntry(route: RouteInfo) {
  const contexts = route.contextMiddleware
    .map((index) => `__DemiurgeMiddlewareContext${index}`);
  const context = contexts.length > 0
    ? contexts.join(" & ")
    : "Record<never, never>";

  return `    ${JSON.stringify(route.pattern)}: ${context};`;
}

function renderMutationMethodsEntry(route: RouteInfo) {
  return `    ${JSON.stringify(route.pattern)}: MutationMethodsOf<typeof import(${JSON.stringify(route.importPath)})>;`;
}

function toConcretePathType(pattern: string) {
  if (!pattern.includes("[")) {
    return JSON.stringify(pattern);
  }

  const parts = pattern.split(/(\[\.\.\.[^\]]+\]|\[[^\]]+\])/g).filter(Boolean);
  return `\`${parts.map((part) => (part.startsWith("[") ? "${PathValue}" : escapeTemplate(part))).join("")}\``;
}

function escapeTemplate(value: string) {
  return value.replace(/[`$\\]/g, "\\$&");
}
