import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";

export type GenerateRoutesOptions = {
  outputFile: string;
  routesDir: string;
};

type RouteInfo = {
  pathVars: string[];
  pattern: string;
};

export async function generateRoutes(options: GenerateRoutesOptions) {
  const routeFiles = await findRouteFiles(options.routesDir);
  const routes = routeFiles
    .map((file) => toRouteInfo(options.routesDir, file))
    .filter((route): route is RouteInfo => Boolean(route))
    .sort((a, b) => a.pattern.localeCompare(b.pattern));

  const source = renderRoutesModule(routes);

  await mkdir(dirname(options.outputFile), { recursive: true });
  await writeFile(options.outputFile, source);

  return {
    routes,
    source,
  };
}

async function findRouteFiles(directory: string) {
  const entries = await readdir(directory, {
    recursive: true,
    withFileTypes: true,
  });

  return entries
    .filter((entry) => entry.isFile() && /\.tsx?$/.test(entry.name))
    .map((entry) => resolve(entry.parentPath, entry.name));
}

function toRouteInfo(routesDir: string, file: string) {
  const relativePath = relative(routesDir, file).split(sep).join("/");
  const fileSegments = relativePath.replace(/\.tsx?$/, "").split("/");
  const basename = fileSegments.at(-1);

  if (basename?.startsWith("@")) {
    return null;
  }

  const urlSegments = fileSegments.flatMap((segment) => {
    if (segment === "index") {
      return [];
    }

    if (segment.startsWith("[...") && segment.endsWith("]")) {
      return [segment];
    }

    if (segment.startsWith("[") && segment.endsWith("]")) {
      return [segment];
    }

    return [segment];
  });

  const pathVars = fileSegments.flatMap((segment) => {
    if (segment.startsWith("[...") && segment.endsWith("]")) {
      return [segment.slice(4, -1)];
    }

    if (segment.startsWith("[") && segment.endsWith("]")) {
      return [segment.slice(1, -1)];
    }

    return [];
  });

  return {
    pathVars,
    pattern: `/${urlSegments.join("/")}`.replace(/\/$/, "") || "/",
  };
}

function renderRoutesModule(routes: RouteInfo[]) {
  return `// Generated by Demiurge. Do not edit by hand.
import "demiurge";
import type { PathValue } from "demiurge";

declare module "demiurge" {
  interface RoutePathVars {
${routes.map(renderPathVarsEntry).join("\n")}
  }

  interface RouteConcretePaths {
${routes.map(renderConcretePathEntry).join("\n")}
  }
}

export {};
`;
}

function renderPathVarsEntry(route: RouteInfo) {
  if (route.pathVars.length === 0) {
    return `    ${JSON.stringify(route.pattern)}: {};`;
  }

  const pathType = route.pathVars
    .map((name) => `${name}: PathValue`)
    .join("; ");

  return `    ${JSON.stringify(route.pattern)}: { ${pathType} };`;
}

function renderConcretePathEntry(route: RouteInfo) {
  return `    ${JSON.stringify(route.pattern)}: ${toConcretePathType(route.pattern)};`;
}

function toConcretePathType(pattern: string) {
  if (!pattern.includes("[")) {
    return JSON.stringify(pattern);
  }

  const parts = pattern.split(/(\[\.\.\.[^\]]+\]|\[[^\]]+\])/g).filter(Boolean);
  return `\`${parts.map((part) => (part.startsWith("[") ? "${PathValue}" : escapeTemplate(part))).join("")}\``;
}

function escapeTemplate(value: string) {
  return value.replace(/[`$\\]/g, "\\$&");
}
